# -*- coding: utf-8 -*-
"""male_female_eye.ipynb
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/17824hG0tuv-XQQDb5Qbpde7qdM9o8Eol
"""

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# ----------------------------------------------------------------------
# Page config
# ----------------------------------------------------------------------
st.set_page_config(
    page_title="Eye Gender Detection",
    page_icon="👁️",
    layout="centered",
)

# ----------------------------------------------------------------------
# Background + custom styling
# ----------------------------------------------------------------------
st.markdown(
    """
    <style>
    .stApp {
        background: linear-gradient(135deg, #1e1e2f 0%, #2b2b45 50%, #1e1e2f 100%);
        color: #f0f0f0;
    }
    .main-title {
        text-align: center;
        font-size: 2.5rem;
        font-weight: 800;
        background: linear-gradient(90deg, #a78bfa, #60a5fa);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin-bottom: 0.2rem;
    }
    .subtitle {
        text-align: center;
        color: #cbd5e1;
        font-size: 1.05rem;
        margin-bottom: 1.5rem;
    }
    .instructions-box {
        background-color: rgba(255, 255, 255, 0.06);
        border: 1px solid rgba(255, 255, 255, 0.15);
        border-radius: 12px;
        padding: 1rem 1.2rem;
        margin-bottom: 1.5rem;
    }
    .result-box {
        background-color: rgba(255, 255, 255, 0.08);
        border-radius: 14px;
        padding: 1.2rem;
        margin-top: 1rem;
        text-align: center;
    }
    .logo-wrap {
        display: flex;
        justify-content: center;
        margin-bottom: 0.5rem;
    }
    .sticker {
        display: inline-block;
        font-size: 1.6rem;
        margin: 0 0.3rem;
        animation: float 3s ease-in-out infinite;
    }
    .sticker:nth-child(2) { animation-delay: 0.5s; }
    .sticker:nth-child(3) { animation-delay: 1s; }
    @keyframes float {
        0%   { transform: translateY(0px); }
        50%  { transform: translateY(-6px); }
        100% { transform: translateY(0px); }
    }
    </style>
    """,
    unsafe_allow_html=True,
)

# ----------------------------------------------------------------------
# Load trained model
# ----------------------------------------------------------------------
@st.cache_resource
def load_model():
    return tf.keras.models.load_model("male_female_eye_model.keras")

model = load_model()
IMG_SIZE = (128, 128)

# ----------------------------------------------------------------------
# Logo (custom SVG, drawn inline — no external image needed)
# ----------------------------------------------------------------------
LOGO_SVG = """
<svg width="90" height="90" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
    <defs>
        <linearGradient id="logoGrad" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" stop-color="#a78bfa"/>
            <stop offset="100%" stop-color="#60a5fa"/>
        </linearGradient>
    </defs>
    <circle cx="50" cy="50" r="48" fill="url(#logoGrad)" opacity="0.15"/>
    <path d="M10 50 C 25 20, 75 20, 90 50 C 75 80, 25 80, 10 50 Z"
          fill="none" stroke="url(#logoGrad)" stroke-width="4"/>
    <circle cx="50" cy="50" r="16" fill="url(#logoGrad)"/>
    <circle cx="45" cy="45" r="5" fill="#1e1e2f"/>
</svg>
"""

st.markdown(f'<div class="logo-wrap">{LOGO_SVG}</div>', unsafe_allow_html=True)

# ----------------------------------------------------------------------
# Header
# ----------------------------------------------------------------------
st.markdown('<div class="main-title">👁️ Male and Female Eye Detection</div>', unsafe_allow_html=True)
st.markdown(
    '<div class="subtitle">Upload a close-up eye image and let the model predict whether it belongs to a male or female.</div>',
    unsafe_allow_html=True,
)
st.markdown(
    """
    <div style="text-align:center; margin-bottom: 1rem;">
        <span class="sticker">✨</span>
        <span class="sticker">🔬</span>
        <span class="sticker">🧠</span>
    </div>
    """,
    unsafe_allow_html=True,
)

# ----------------------------------------------------------------------
# Instructions
# ----------------------------------------------------------------------
with st.container():
    st.markdown(
        """
        <div class="instructions-box">
        <b>📋 How to use:</b>
        <ol>
            <li>Click <b>Browse files</b> below and select a clear, close-up eye image (JPG or PNG).</li>
            <li>Wait a moment while the model processes the image.</li>
            <li>View the predicted gender and the model's confidence score.</li>
        </ol>
        <b>💡 Tip:</b> Well-lit, front-facing, cropped eye images give the most accurate predictions.
        </div>
        """,
        unsafe_allow_html=True,
    )

# ----------------------------------------------------------------------
# File uploader
# ----------------------------------------------------------------------
uploaded_file = st.file_uploader(
    "Choose an eye image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")
    st.image(image, caption="Uploaded Image", use_container_width=True)

    # Preprocess image
    img = image.resize(IMG_SIZE)
    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    # Prediction
    with st.spinner("Analyzing the image..."):
        prediction = model.predict(img_array)
        probability = prediction[0][0]

        if probability > 0.5:
            label = "👨 Male Eye"
            confidence = probability
        else:
            label = "👩 Female Eye"
            confidence = 1 - probability

    # Live notification after prediction
    st.toast(f"Prediction complete: {label}", icon="✅")

    # Result display
    result_stickers = "👨‍🦱 💙 ✨" if probability > 0.5 else "👩‍🦰 💜 ✨"
    st.markdown('<div class="result-box">', unsafe_allow_html=True)
    st.subheader("🔍 Prediction Result")
    st.markdown(f'<div style="font-size:1.4rem;">{result_stickers}</div>', unsafe_allow_html=True)
    st.success(label)
    st.write(f"**Confidence:** {confidence * 100:.2f}%")
    st.progress(float(confidence))
    st.markdown('</div>', unsafe_allow_html=True)

else:
    st.info("👆 Upload an eye image above to get started.")
